transaction = int(input("have you having any issue with transaction = \n 1. yes \n 2.no \n enter = "))
if transaction == 1:
    issue = int(input("please enter what issue did you face \n 1. issues with failed payments \n 2. issues with pending payments \n 3. issues with successful payments \n 4. issues with payments made to merchants \n 5. issues with refund \n enter ="))
    if (issue == 1 ):
        failed = int(input("what failed payment did you want to see \n 1. why did my UPI payment fail ? \n 2. why is my money deducted for my failed payment ? \n 3. why is my money not refunded yet ? \n 4. where can in find the UTR number for this payment \n enter ="))
        if(failed ==1):
            print("Why did my UPI payment fail? /n Your UPI payment on PhonePe may have failed due to any one of the below reasons:/n• UPI network issues\n• Technical issues with the banks\n• Wrong UPI PIN • Not enough balance in your bank\n account • Bank or UPI limits reached\n• Security reasons\n• Other bank account-related issues\nImportant: You can try making the payment again after checking the reason for failure within the History section of your PhonePe app.\nLearn more about refunds for failed UPI payments.")
        elif(failed == 2):
            print("Why is my money deducted for my failed payment?\nIf your money is deducted from your bank account for a failed payment, there is no need to worry as your money is absolutely safe with your bank. The amount will be refunded into your account within 3 to 5 days from the date you made the payment. You can check your relevant bank account statement after 5 days for a refund confirmation.\nIn the unlikely event that your bank fails to refund the amount within 5 days from the payment date, please contact them with the Unique Transaction Reference (UTR) number for the payment. They will help you with this.\nNote: In some error scenarios, your bank may refund your deducted amount immediately. As you may experience a delay in receiving an SMS from your bank about such refunds, we recommend that you check the relevant")
        elif(failed ==3):
            print("Why is my money not refunded yet?\nFor failed UPI payments, banks usually refund the money anywhere between 3 to 5 days from the time of payment. Please check your bank account statement after 5 days.\nIn case you haven't received the refund even after 5 days, please contact your bank with the Unique Transaction Reference (UTR) number for the payment.\nNote: You may experience a delay in receiving an SMS from your bank about such refunds, we recommend that you check the relevant account statement for a confirmation.\nLearn more about finding the UTR number for your failed payment.")
        elif(failed == 4):
            print("Where can I find the UTR number for this payment?\nTo find the UTR number for your failed payment,\n1. Tap History on your PhonePe app\nhome screen.\n 2. Select the failed payment for which you\n would like to view the UTR number.\n3. You will see the12-digit UTR number in\nthe Debited from section on thescreen.")
        else:
            print ("enter some valid reason or number")
    elif(issue == 2):
        payment = int(input("what payment issue did you have \n 1. why my UPI payment pending ? \n 2. what do i do if my UPI payment is pending ? \n 3. why do i have to wait for 48 to know the final payment status ? \n 4. how do i cancel my pending payment ? \n 5. what if my payment is pending for more than 48 hours \n enter = "))
        if (payment == 1):
            print("Why is my UPI payment pending?\nBanks usually complete UPI payments instantly. In rare cases, due to technical issues, banks may take additional time to deposit the payment money into the receiver's account. In such cases, it's recommended that you wait for 48 hours from the time of payment to know the final status.\nLearn more about what you can do if your payment is pending.")
        elif(payment == 2):
            print("What do I do if my UPI payment is pending? If your UPI payment is pending,\nyou will need to wait for 48 hours for your bank to update\nthe final status of the payment.\nAfter 48 hours, the bank may update the status of your pending payment as either successful or failed. If your payment is marked successful, the payment amount will be deposited into the receiver's account. If your payment is marked as failed, the payment amount will be refunded to your account within 3 to 5 days from the payment date.\nWe will notify you about the status of your pending payment as soon as the bank updates it. Alternatively, you can check the status in the History section of your PhonePe app.\nImportant: Your money is absolutely safe with the bank, and will reach the receiver's")
        elif(payment == 3):
            print("Why do I have to wait for 48 hours to know the final payment status?\nAs per current banking timelines, for pending payments, banks can take anywhere between 2 minutes and 48 hours from the time of payment to confirm the final status. This is completely dependent on the bank.")
        elif(payment ==4 ):
            print("How do I cancel my pending payment?\nYou can't cancel UPI payments once initiated as they are direct bank-to-bank transfers. We request that you wait for 48 hours from the time you made the payment to know if your payment is successful or has failed.\nNote: If your pending payment fails, your entire amount will be refunded to your account within 3 to 5 days.")
        elif(payment == 5 ):
            print("What if my payment is pending for more than 48 hours?\nBanks usually confirm the final payment status within 48 hours from the time you made the payment. If you see that your payment is still marked as pending in the History section of your PhonePe app after 48 hours, please tap the button below and create a ticket. We will escalate this issue with the banking authorities on your behalf.")
        else:
            print("enter some valid reason or number")

    elif(issue == 3):
        successfull = int(input("please enter what successfull payment issues did you face \n 1. payment made to a phone number or UPI IP (VPD) \n 2. payment made to a bank account \n enter = "))
        if(successfull==1):
            upi = int(input("please enter what phone number payment issue did you face\n 1. what if i've sent money toa wrong phone number or UPI ID (VAP)? \n 2. what if my payment is succesfull but tha money has not reached to the receiver? \n 3. why do bank takes upto 5 days to deposit the money ? \n 4. can i cancel a successfull payment i made using a phone number or UPI ID ? \n 5. how does the reciver know into which account the money is deposited ? \n 6. what if the money is not depositec into the receiver's account after 5 days \n enter = "))
            if (upi == 1):
                print("what if i've sent money toa wrong phone number or UPI ID (VAP)\n In the unfortunate event that you've sent money to a wrong phone number or UPI ID (VPA), we request that you contact your bank directly and raise a wrong credit charge bank with the Unique Transaction Reference (UTR number for the payment. \n\n In case the person you've incorrectly sent money to holds an account with bank , your bank can directly contact them on your behalf and request them to reverse the money to you \n In case the person you've incorrectly set money to holds an account the another bank , your bank can only act as a facilitator, and provide you with some details of the branch . you will need to visit the branch and speak to the manager for further assistance . \n\n note : the money can only be reversed if the receiver agrees . if they do , the money will reach your account within 7 days )")
            elif ( upi ==2 ):
                print("what if my payment is succesfull but tha money has not reached to the receiver? A payment is marked successful on phonepe only after we receive a confirmatio from the receive's bank that the money has reached them . Bank usually deposity the money into the reciver's account insultly for UPI payments. In rare casesm due to technical issues, they may take upto 5 days from the payment date to deposit the money . Please ask reciver to check the relevant bank  account statement after 5 days for a confirmation . \n note :if you've sent money to a phonepe user oe phonepeUPI ID , the money will be credited to the bank account that the receiver set as theri primarybank account on the time of payment details  ")
            elif(upi ==3):
                print("Why do banks take upto 5 days to deposit the money?\n\nBanks usually deposit the money for UPI payments instantly. However, due to some technical issues in the banking system, they may take upto 5 days from the payment date to deposit the money into the receiver's account. This is completely dependent on the bank.")
            elif(upi == 4):
                print("Can I cancel a successful payment I made using a phone number or UPI ID?\nNo, you can't cancel UPI payments once initiated as they are direct bank-to-bank transfers. We recommend that you ask the receiver to check the relevant bank account statement after 5 days from the payment date for a deposit confirmation.\nImportant: If the bank fails to deposit themoney into the receiver's account after 5 days, please ask them to contact their bank with the Unique Transaction Reference (UTR) number for help with the payment.")
            elif(upi ==5):
                print("How does the receiver know into which account the money is deposited?\nIf you've sent money using a PhonePe registered mobile number or UPI ID, the money will be credited to the bank account that the receiver set as their primary bank account on PhonePe at the time of payment. The receiver can view the payment details within the History section of their PhonePe app to know into which account the money is deposited.\nIf you've sent money to a non-PhonePe UPI ID, please ask the receiver to check the statement of the bank account that is linked to hat UPI ID.")
            elif(upi ==6):
                print("What if the money is not deposited into the receiver's account after 5 days?\n\nIn the rare case that the receiver's bank fails to deposit the money after 5 days, please ask the receiver to contact their bank with the Unique Transaction Reference (UTR) number for the payment. Their bank will be in the best position to help them with this.\nTo find the UTR number,\n\n1. Tap History on the PhonePe app homescreen . \n2. Select the payment for which you wouldlike to view the UTR number.\n\n. You will see the 12-digit UTR number in the Debited from section on the screen.\n\nNote: The receiver may experience a delay in receiving an SMS from their bank for payments, we recommend that you ask them to check the relevant account statement for a credit confirmation.")
            else:
                print("please enter the valid numbers ")
        elif(successfull== 2):
            upi = int(input("please enter what is payment made to back account \n 1. what if i've sent money to wrong bank account ? \n 2. what if payment is successful but the money has not reached the receiver ? \n 3. why do banks takes upto  5 days to deposit the money ? \n 4 . can i cancel a successful payment i made to a bank account ? \n 5. what if the money is not deposit into the receiver's account after 5 days ? \n enter "))
            if ( upi == 1):
                print("What if I've sent money to the wrong bank account?\nIn the unfortunate event that you've sent money to a wrong bank account, we request that you contact your bank directly and raise a wrong credit chargeback with the Unique Transaction Reference (UTR) number for the payment.\nIn case the person you've incorrectly sent money to holds an account with your bank, your bank can directly contact them on your behalf and request to reverse the money to you.\nIn case the person you've incorrectly sent money to holds an account with another bank, your bank can only act as a facilitator, and provide you with some details of the branch. You will need to visit the branch and speak to the manager for further assistance.\nNote: The money can only be reversed if the receiver agrees. If they do, the money will reach your account within 7 days.")
            elif(upi == 2):
                print("What if my payment is successful but the money has not reached the receiver?\n\nA payment is marked successful on PhonePe only after we receive a confirmation from the receiver's bank that the money has reached them. Banks usually deposit the money into the receiver's account instantly for UPI payments. In rare cases, due to technical issues, they may take upto 5 days from the payment date to deposit the money. Please ask the receiver to check the relevant bank account statement after 5 days for a deposit confirmation.\nNote: Please check the payment details within the History section of your PhonePe app to ensure that you've sent the money to the correct account. Alternatively, you can,\n\n1. Tap To Account on the PhonePe app home screen.\n2. Tap the 3 dots next to the relevant bank account.\n3. Select Edit from the options listed.")
            elif(upi == 3):
                print("Why do banks take upto 5 days to deposit the money?\n\nBanks usually deposit the money for UPI payments instantly. However, due to some technical issues in the banking system, they may take upto 5 days from the payment date to deposit the money. This is completely dependenton the bank..")
            elif(upi ==4):
                print("Can I cancel a successful payment I made to a bank account?\n\nNo, you can't cancel UPI payments once initiated as they are direct bank-to-bank transfers. We recommend that you ask the receiver to check the relevant bank account statement after 5 days from the payment date for a deposit confirmation.")
            elif(upi == 5):
                print("What if the money is not deposited into the receiver's account after 5 days?\n\nIn the rare case that the receiver's bank fails to deposit the money after 5 days, please ask the receiver to contact their bank with the Unique Transaction Reference (UTR) number for the payment. Their bank will be in the best position to help them with this.\nNote: The receiver may experience a delay in receiving an SMS from their bank for payments, we recommend that you ask them to check the relevant account statement for a credit confirmation.")
            else:
                print("please enter the valid numbers ")
        else :
            print("please enter the valid numbers")
    elif(issue == 4):
        payment = int(input("issue with payments made to merchants \n 1. what if the merchant denies having received the amount for a successful payment \n 2. what if i have paid twice for an order or booking ? \n 3. what if the order or booking is not confimed for a successful payment ?"))
        if (payment == 1):
            print("What if the merchant denies having received the amount for a successful payment?\nA payment is marked successful on PhonePe only after we receive a confirmation that the money has reached the merchant. However, merchants don't inform us if they have confirmed your order or offered the service that you've paid for.\nIn case the merchant denies having received the money, to please tap the button below and create a ticket for the relevant payment. This will help us better assist you.")
        elif(payment == 2):
            print("What if I have paid twice for an order or booking?\nIf you have paid twice for an order or booking, we request that you contact the merchant directly and inform them about the double payment. The merchant should refund the excess amount you've paid after checking their payment records.\nIn the unlikely event that the merchant refuses to refund the amount, please contact your bank directly and raise a complaint with the Unique Transaction Reference (UTR) number for the relevant payment. Your bank will be in the best position to help youwith this.\n\nNote: To avoid such incidents in the future, we recommend that you check the final payment status before trying to make the payment again.")
        elif(payment == 3):
            print("What if the order or booking is not confirmed for a successful payment?\nIf the merchant fails to confirm your order or booking, we request that you contact them directly for an update.\n\nWhile PhonePe takes complete responsibility for any payment-related issues, the merchant on whose app you placed your order or made a booking will be better placed to resolve any order-related or booking-related issues.\nFor example, if a PNR number is not generated for your IRCTC ticket booking within 20 minutes from the time of payment, IRCTC will initiate a refund to you within 2 days. You will receive a refund based on the payment mode you used: UPI - 3 to 5 days Debit/Credit Cards - 7 to 9 days Wallets - 24 hours")
        else:
            print("please enter the correct value ")
    elif(issue== 5):
        refund = int (input("please enter the issue \n 1. Refunds for upi payments \n 2. Refunds for card payments \n 3. Refunds for payments made to a merchant \n enter = "))
        if (refund == 1):
            up = int(input("please enter what issue did you face is upi payment \n 1. when will i refund for a failed upi payment ? \n 2. what if i don't recive the refund after 5 days for a failed upi payment ? \n enter =  "))
            if (up == 1):
                print("When will I receive a refund for a failed UPI payment?\nIf your UPI payment fails for any reason, there is no need to worry as your money is absolutely safe with your bank. Your bank will automatically refund the money to your account within 3 to 5 days from the date you made the payment. You can check your relevant bank account statement after 5 days for a confirmation.\nNote: In some cases, your bank may refund the deducted amount immediately. As you may experience a delay in receiving an SMS from your bank about such refunds, we recommend that you check the relevant account statement for a confirmation.")
            elif(up == 2):
                print("What if I don't receive the refund after 5 days for a failed UPI payment?\n\nIn the rare case that your bank doesn't refund your money after 5 days for a failed UPI payment, please contact your bank with the 12-digit Unique Transaction Reference (UTR) number. As refunds are processed by banks, they are better placed to help you with this.")
            else:
                print("please enter the valid number ")
        elif(refund == 2):
            up = int(input("please enter the issue \n 1. what will i receive a refund for a failed card payment ? \n 2. what if i didn't recive the refund after 9 days for a failed card payment ? "))
            if (up == 1):
                print("When will I receive refund for my failed card payment?\n\nIf a payment you have made using a debit or credit card fails for any reason, there is no need to worry. Your money is absolutely safe with the bank and will be refunded to you within 7 to 9 days from the date you made the payment. Please check the relevant account statement after 9 days for a confirmation.")
            elif(up == 2):
                print("What if my money is not refunded after 9 days for a failed card payment?\n\nIn the rare case that your money is not refunded even after 9 days from the payment date, please contact your bank with the refund reference number for this payment. Your card-issuing bank is better placed to share a status on your refund.")
            else:
                print("please enter the valid number ")
        elif(refund == 3):
            print("When will I receive a refund for a cancelled or failed order/booking or payment?\n\nIf your order/booking or merchant payment is cancelled or has failed, there is no need to worry. The merchant will automatically refund the money to you. We request that you contact the merchant directly as they will be able to share a status on your refund.\nNote: The merchant will refund the money to the account from which you made the payment.")
    else :
        print("please enter the valid number ")
elif(transaction == 2):
    print("thanks for your feedback sir")
else :
    print("please enter the valid number ")
